### ISSUE TITLE
US-009 Filter Events Through Date

### ISSUE THREAD

**Issue by 0-Gixty-0** [willayy/DAT257-Agile#14]
As a user I want to be able to filter the police events through single dates and an interval of time so that I can see which events have happened during a certain period or day.

### Because
Filtering by dates is a basic feature and should be implemented. The date of events is already part of the JSON from the api and should be utilized accordingly
### Tasks

- [x] Create single date selection
- [x] Create date range selection
- [x] Events should be filtered by the active date(s) selection
- [ ] Integrate date selection(s) into the API fetch url

### Acceptance criteria

- The date selection should be visible on screen.
- Selecting dates should be intuitive and simple
- Only events on the selected date or range should be listed in the ListView component
- Fetching events through date selection shows only the events taken from the API for those date(s)
