### ISSUE TITLE
US-010 Line Plot Of Event Frequency For Event Type(s)

### ISSUE THREAD

**Issue by 0-Gixty-0** [willayy/DAT257-Agile#15]
As a crime analyst I want to be able to create a line plot depicting the frequency of reported events of a certain type over a certain time interval so that I can skip having to create the code and line plot myself

### Because
Visualization features are an important to making the application more useful with respect to UN goal 16. The ability to quickly create line plots using the data with different parameters makes it easier for both the average user and more advanced users to understand how crime is developing in Sweden.
### Tasks

- [ ] Create visualizations page with title
- [ ] Create event type selector
- [ ] Create date range selectors
- [ ] Create _Create Plot_ button
- [ ] Write and integrate code for generating a line plot with given parameters
- [ ] Make the line plot displayable on screen 

### Acceptance criteria

- User is able to select event category and date range for the line plot
- The desired plot should be displayed on screen upon clicking the _create_ button

**Comment by jmarkusson** [comment]
Visualizations page is created along with Create plot button and the selectors for crimetype and location, also the component Linegraph which can create a graph based on the selectors from the viz page. Not done yet

Put on hold since we dont have enough data to plot from the fetching, continue when that is resolved.
