### ISSUE TITLE
US-011 Statistic Generation

### ISSUE THREAD

**Issue by 0-Gixty-0** [willayy/DAT257-Agile#16]
As a crime interested statistician I want to see basic crime statistics from the police events so that I can find lay a basis for my own research. 

### Because
It is difficult to visualize the available data from the police API since there are very many locations and categories to look through. Therefore simple statistics is a fitting way to present the large amount of events in a more concise and understandable way. These number can then be used in further reading or research outside of the application
### Tasks

- [x] Create a prototype of the statistics view
- [x] Create a _Statistics Generation_ page
- [x] Fill page with information on what the tool does and how to use it (HOW-TO)
- [x] Create event type selector
- [x] Create location selector
- [x] Create _Generate Statistics_ button
- [x] Write and integrate code for generating the following statistics:

1. Most frequent event type (All of Sweden or selected location)
2. Least frequent event type (All of Sweden or selected location)

- [x] Make the statistics visible on screen upon generation

### Acceptance criteria

- All of the selectors are present and function correctly
- Statistics can be generated
- All statistic types can be generated
- Statistic types that can only be generated with certain selection are the only generated statistics.
- The statistics are visible on screen

**Comment by 0-Gixty-0** [comment]
I invite all members of the group to comment on which types of statistics would be considered relevant or interesting. These are the ones I came up with when writing the user story. I am certain there are many more that I haven't considered

**Comment by 0-Gixty-0** [comment]
These statistics were removed upon creating the date selector as a separate user story:
1. _Rare Crimes_ list of event types that have not been listed in an event for selected date(s) (All of Sweden or selected location)
2. Location with most events listed for date(s) (Cannot be combined with a selected location)
3. Location with least events listed for date(s) (Cannot be combined with a selected location)
4. Location with most events listed for date(s) for selected event type (Cannot be combined with a selected location)
5. Location with least events listed for date(s) for selected event type (Cannot be combined with a selected location)
