### ISSUE TITLE
US-012 Create About Page

### ISSUE THREAD

**Issue by 0-Gixty-0** [willayy/DAT257-Agile#17]
As a very appreciative user I want there to be able to learn who created the application so that I can contact them and tell them how great their app is

### Because
An about page with contact information is standard for any web-page worth it's merit.
### Tasks

- [ ] Create _About Us_ page
- [ ] In the page explain what the application is and what it aims to achieve
- [ ] Include contact information for all members of the group

### Acceptance criteria
The _About Us_ page accurately describes the projects purpose and how to use the application. It also contains correct contact information for each member of the group.
