### ISSUE TITLE
US-013 Fetch Events Through Date

### ISSUE THREAD

**Issue by 0-Gixty-0** [willayy/DAT257-Agile#23]
As a historian I want to be able to see which events happened on certain dates or between certain dates so that I can document the history of police events over time

### Because
This feature is useful since it utilizes more of the available data fetched from the police API.
### Tasks

- [ ] Create a specific date selector combobox
- [ ] Create a date range selector (can utilize two of the above comboboxes)
- [ ] Integrate date selection(s) into the api fetch url

### Acceptance criteria

- Selectors are visible on the screen
- Fetching events through date selection shows only the events taken from the API for those date(s)

**Comment by 0-Gixty-0** [comment]
Duplicate. See #14
