### ISSUE TITLE
getCrimeData is invalid

### ISSUE THREAD

**Issue by willayy** [willayy/DAT257-Agile#33]
### Background
The method getCrimeData does not work as we intended. The Swedish police api only returns the latest 500 events which is not the 6 months of data we hoped for. By using the DateTime parameter we can fetch 500 events per day which could be used to generate a backlog of fetches ranging back 3-6 months, the only problem with this is that we have to respect the API limits so fetching this data dynamically will take 1.5-3 hours. Fetching the data and storing it in some kind of persistence storage, however, increases the complexity a lot and therefore its not really viable for the **whole** project scope.

~Everything considered we will fetch the data dynamically and have a list that expands slowly if you are visiting the website for the first time.~

As a user I want to see a longer timeframe of data 
### Because
so I can draw real conclusions from the data

### Tasks
- [ ] Make a sub-program that runs in parallell with the web app, fetching more and more data the longer it stays running.
- [ ] Store fetched data in a folder of .json files, the name of the file should be the fetch date.
- [ ] Ensure sub-program does not violate API limits when fetching such high amounts of data.
- [ ] Remake the "API" function that gives data to the frontend. Now it should fetch from the persistent store of .json files.
