### ISSUE TITLE
US-016 Create Heat Map

### ISSUE THREAD

**Issue by jmarkusson** [willayy/DAT257-Agile#34]
As a geographic displayed data enjoyer i want a heat map that displays the crime data so that I can easily see the amount of a certain crime type in a specific "kommun"

### Because
Visualizing crime data on a heat map provides a clear and intuitive way to understand the distribution and intensity of different types of crimes within each "kommun".

### Tasks
- [x] Create a "karta" page
- [x] Fetch data from a map API 
- [x] Make the map visible on the page
- [x] Input the crimeSelector so the user can select crime type
- [x] Determine appropriate color scale for representing crime intensity levels
- [x] Display the color-scale on the page 
- [x] Provide implementation so each kommun gets colored differently based on the crime-rate of a certain crime type based on the figma design from US-020

### Acceptance criteria
The color-coded heat map accurately represents the intensity of the selected crime type in each "kommun."
Users can interact with the heat map and view detailed crime information.
The color-coded heat map feature is integrated seamlessly into the geographic data display page.
User interface elements for crime type selection is intuitive and functional.

**Comment by 0-Gixty-0** [comment]
Useful links for this issue:
Sweden Geo-json: https://github.com/okfse/sweden-geojson
LeafletJS heatmap example: https://leafletjs.com/examples/choropleth/
