### ISSUE TITLE
US-018 Add UN Sustainable development Goal to About Page

### ISSUE THREAD

**Issue by maxdreifeldt** [willayy/DAT257-Agile#35]
As a developer I want to show the puropse behind our project, by showcasing what UN Sustainable Development Goal were trying to solve

### Because
I want to spread awareness about where and what types of crimes are committed
### Tasks

- [x] Create a new section in the about page
- [x] Write what UN Sustainable Development Goal our project aligns with
- [x] Add CSS to make it fit the page

### Acceptance criteria

The section accurately describes the projects alignment with the UN Sustainable Development Goal and is visable on screen
