### ISSUE TITLE
US-023 Make map interactive

### ISSUE THREAD

**Issue by maxdreifeldt** [willayy/DAT257-Agile#55]
As a user, I want to be able to interact with the map because I want to see which municipality or region is which.

This user story is important since it gives users with limited geographical knowledge accessibility to the application.

### Tasks

- [x] Add markers to highlighted location
- [x] Add text including name of location to markers
- [x] Add button to show and hide markers

### Acceptance criteria
When only markers for highlighted regions or municipalities, those with events reported, are shown on screen with accompanying popup text including location name and number of events
